[package]
name = "color"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.126"
js-sys = "0.3"

[dependencies.console_error_panic_hook]
version = "0.1"
optional = true

[features]
default = []
debug = ["dep:console_error_panic_hook"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
